---
- name: Working with AWS EC2 Instance
  hosts: localhost
  vars_files:
    - aws_credentials.yml
  vars:
    - instance_type: 't2.micro'
    - instance_image: 'ami-052efd3df9dad4825'
    - AWS_key: 'AWS_ax'
    - region: 'us-east-1'
    - instance_name:
      - 'server_build'
#      - 'server_prod'

  tasks:

    - name: Create ec2 instance
      ec2_instance:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        instance_type: '{{ instance_type }}'
        image_id: '{{ instance_image }}'
#        count: 1
        key_name: '{{ AWS_key }}'
        wait: true
        region: '{{ region }}'
        name: '{{ instance_name }}'

    - name: Info instance
      ec2_instance_info:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        region: '{{ region }}'
      register: ec2_info

    - name: show Info
      ansible.builtin.debug:
        var: ec2_info
