---
- name: Provision AWS EC2 Instances
  hosts: localhost
  vars_files:
    - aws_credentials.yml
  vars:
    - instance_type: 't2.micro'
    - instance_image: 'ami-052efd3df9dad4825'
    - region: 'us-east-1'

  tasks:
    
    - name: Create a new ec2 key
      ec2_key:
        name: 'aws_test_key'
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        region: '{{ region }}'
      register: key_info

    - name: Save private key
      copy: 
        content: '{{ key_info.key.private_key }}' 
        dest: '{{ ansible_user_dir }}/.ssh/aws_test_key'
        mode: 0600
      when: key_info.changed

    - name: show key_info
      ansible.builtin.debug:
        var: key_info

    - name: Create ec2 instance
      ec2_instance:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        instance_type: '{{ instance_type }}'
        image_id: '{{ instance_image }}'
        key_name: 'aws_test_key'
        region: '{{ region }}'
        count: 2
      register: ec2_info

#    - name: Info instance
#      ec2_instance_info:
#        aws_access_key: '{{ aws_access_key }}'
#        aws_secret_key: '{{ aws_secret_key }}'
#        region: '{{ region }}'
#      register: ec2_info

    - name: show Info
      ansible.builtin.debug:
        var: ec2_info
